application: erin-and-jay
version: 1.1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|ttf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|ttf))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.application