application: erin-and-jay
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|ttf|json|ctp|svg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|ttf|json|ctp|svg))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: main.application