<p class="middle">
	On August 25th, 2013, amongst “Diamonds in the Sky” fireworks, Jason asked Erin to be his wife. They both look forward to having you join them on the day that marks the first step of their journey together as Husband and Wife…
</p>